export const ActionTypes = {
    FETCH__TOPPLACES:'FETCH__TOPPLACES',
    SET__TOPPLACES: 'SET__TOPPLACES',
    SELECTED__TOPPLACE: 'SELECTED__TOPPLACE',
    REMOVE__SELECTED__TOPPLACE:'REMOVE__SELECTED__TOPPLACE',

    FETCH__INFO:'FETCH__INFO',
    SET__INFO:'SET__INFO',

    FETCH__GUESTS__COMMENTS:'FETCH__GUESTS__COMMENTS',
    SET__GUESTS__COMMENTS:'SET__GUESTS__COMMENTS',

    SET__TOURS:'SET__TOURS',
    SELECRED__TOUR:'SELECRED__TOUR',
    REMOVE__SELECTED__TOUR:'REMOVE__SELECTED__TOUR',

    SET__BLOG:'SET__BLOG',
    SELECTED__BLOG: 'SELECTED__BLOG',
    REMOVE__SELECTED__BLOG:'REMOVE__SELECTED__BLOG',

    FETCH__ABOUT__KYRGYZSTAN:'FETCH__ABOUT__KYRGYZSTAN',
    SET__ABOUT__KYRGYZSTAN:'SET__ABOUT__KYRGYZSTAN'

    

}